### ISSUE TITLE
Mencari Refenrensi Project

### ISSUE THREAD

**Issue by zhaiid** [zhaiid/dokteronline#1]
Disini kita cari referensi project dokter online, silahkan cari website yang menyediakan fasilitas konsultasi dokter online dan di review kelebihan nya apa, ditulis di doc dan di upload disini.

**Comment by harisbook** [comment]
Ok note

**Comment by zhaiid** [comment]
[Referensi UDoctor.docx](https://github.com/zhaiid/dokteronline/files/500029/Referensi.UDoctor.docx)

**Comment by zhaiid** [comment]
closed
